spring.application.name=ewm-main-service
server.port=8080

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hmstr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate & SQL
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true

# ??????????
stats.server.url=${STATS_SERVER_URL:http://localhost:9090}