spring.application.name=ewm-stats-server
server.port=9090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db-stats:5432/stats
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.show-sql=true